### ISSUE TITLE
Can't moderate my own challenge

### ISSUE THREAD

**Issue by DustVoice** [igrigorik/vimgolf#260] opened 2018-11-22 13:55 UTC
It is mentioned in the FAQ that the creator of a challenge is also a moderator of this challenge, who can view/delete any submissions. Unfortunately, I could neither view nor delete any entries. https://www.vimgolf.com/challenges/5ba020f91abf2d000951055c This is my challenge. Asked a moderator on Twitter about this and he told me to file an issue.

**Comment by Hettomei** [comment] 2018-11-22 16:58
Hi

Please click on the entry on 'comment' link

The div should display a new button to delete the entry

**Comment by TitouanT** [comment] 2019-02-28 13:03
@Hettomei, I think you misunderstood what DustVoice wants.
He is not asking about how to delete his entry to any challenge, but how to delete any entry to his challenge.

**Comment by Hettomei** [comment] 2019-02-28 16:03
I can't run a dev env right now. But I think their is a bug in the code : 

app/views/shared/_submissions.erb
```
    <% if submissions.player_can_delete?(solution) %>
      <%= link_to "Delete Entry", delete_entry_path(submissions.challenge_id, solution.id), :class => 'action delete' %>
    <% end %>
```

Then "submissions.player_can_delete?" is at app/services/submissions.rb : 
```
  def player_can_edit?(solution)
    player && (
      player.admin? || creator? || solution.owner?(player)
    )
  end
  alias :player_can_delete? :player_can_edit?

  def user_id
    @user_id ||= Challenge.only(:user_id).find(challenge_id)
  end

  def creator?
    user_id == player.id
  end

```

Maybe there is a bug in `@user_id ||= Challenge.only(:user_id).find(challenge_id)`
I don't think this `find` return only an id, I think it is an object, so    `user_id == player.id` is always false

But two long I did not touch ruby / rails so I can't remember without a repl the behavior of Model.only(foo).find(bar)

**Comment by igrigorik** [comment] 2019-03-02 18:24
@Hettomei I think you're right.. 

>  irb(main):002:0> Challenge.only(:user_id).first
=> #<Challenge _id: 4d1a1c36567bac34a9000002, created_at: nil, updated_at: nil, title: nil, description: nil, diff: nil, input: nil, input_type: nil, output: nil, output_type: nil, user_id: BSON::ObjectId('4d195e75aabf524b07000001')>

Do you have bandwidth to wire up a fix for this?

**Comment by Hettomei** [comment] 2019-03-02 19:29
I would say in 2 weeks

**Comment by Hettomei** [comment] 2019-03-03 21:48
I can't let such a nice site with this ugly bugs. I try a patch now.

**Closed** 2019-03-04 01:28 UTC

**Comment by Hettomei** [comment] 2019-03-04 15:17
The issue is 'closed' but I still need to send the code to vimgolf.com

I plan to do it today or tomorrow (2019-03-05)

**Comment by Hettomei** [comment] 2019-03-04 21:44
It is deployed to http://www.vimgolf.com
@DustVoice feel free to re-open if you still can't moderate your challenge.
