### ISSUE TITLE
add pagination of answers for less memory usage on the heroku dynamo, to prevent the many "Application Error" sent by heroku

### ISSUE THREAD

**Issue by towc** [igrigorik/vimgolf#229] opened 2018-04-02 08:24 UTC
As of the writing of this, whenever you load a challenge on the web, all of the reachable solutions (+ leaderboard) are sent to the client, at once.

A better solution would be to send the client maybe only the top 50 reachable solutions, and giving the user an option to load more of them (only every 50 at a time), and only displaying the top 100 people in the leaderboard.

This way heroku doesn't need to load into memory and transmit all of that information at once, making the site much faster, consuming less internet on the client, and finally not receiving "Application Error" the huge majority of the time, on challenges with more than ~5000 answers

**Comment by igrigorik** [comment] 2018-04-02 14:56
+1 to that! Would you be interested in contributing / tackling this one? :)

**Comment by towc** [comment] 2018-04-02 16:57
Sadly I don't use ruby on rails, and don't have the time/willpower to learn it :/
I would be interested in porting the whole project to node, which would mean probably a lot more people can contribute to it, but I'd understand if you wouldn't want to scrap your code, as well as the contributors'

**Comment by igrigorik** [comment] 2018-04-02 18:49
Yeah, that's probably a big undertaking.. That said, what would you port it to? :)

**Comment by towc** [comment] 2018-04-02 19:29
would be node

**Comment by h43z** [comment] 2018-04-02 20:05
Is a realtime framework really needed for vimgolf?

**Comment by towc** [comment] 2018-04-02 20:10
If you want to keep the RoR feeling. Also, it would be nice to have the list updated without needing to reload the page, for example. We really don't need to use Sails, and I advise against it, but it might help the RoR contributors

**Comment by igrigorik** [comment] 2018-04-03 02:50
Adding pagination and such does not require that we rewrite the entire site :-). Note that the added complexity here is that we rely on same parse+processing code both on the client and server. Rewriting all that is a big undertaking, and I'm personally not convinced that the benefits are worth it.

The underlying performance reasons have nothing to do with Rails or Mongo, but with the simple architecture that I picked back when I built the prototype — it served its purpose better than I ever expected, and now we need to do some work to rework it.

Let's keep this bug open as a feature request, but we don't need to throw the full stack to get it done.

**Comment by towc** [comment] 2018-04-03 08:18
I mostly suggested it as a joke, because I can't really contribute on ruby :P 
I agree

**Comment by Alaya** [comment] 2018-04-16 03:14
I hope you treat it as more than a feature request, because the application errors are miserable for me as a newbie, and make the site almost unusable. I know MongoDB but not Ruby, sadly.

**Comment by Hettomei** [comment] 2018-04-18 18:26
Because it broke my heart to see such a good game crashing chrome on a simple url like : https://vimgolf.com/challenges/55b18bbea9c2c30d04000001 I want to try this feature.

If anybody wants to help, here is my personal roadmap:

- upgrade gem mongoid/mongo/bson and fix home page after the upgrade (PR in progress with good results)
- paginate the home page
- paginate /challenge/:id

Why going through 'paginate home page' :
It is just for me : I take a simple case to better understand monto/mongoid and guess if we need a gem to paginate or do it by hand. (And @igrigorik can refuse the PR of course)

On challenge/:id it is slightly more complicated :

- need to paginate entries
  - when not connected
  - when connected
- need to paginate users (on the right)

**Comment by Hettomei** [comment] 2018-04-20 17:24
I converted every 'ruby code' called on home page into mongo db 'aggregate' function. 

So I can paginate using mongodb skip/limit. I need to add some javascript / and update spec before pushing code.

I m pretty confident for the challenge page.

 I hope to push pr in  month max. Ping me to remotivate me :)

**Comment by Hettomei** [comment] 2018-04-24 12:03
Duplicate of #225

**Comment by Hettomei** [comment] 2018-05-24 07:57
For people comming here.

There is a first attempt at paginate leaderboard using mongodb query : #234 
No need to master ruby, only a mongodb master to review/improve the query

**Comment by Hettomei** [comment] 2018-06-10 00:21
@igrigorik 
Question here : 

I try to paginate solutions. Do you want to keep
```
# Challenge#allowed_entries
solution_offset = [index - 5, 0].max
``` 
This lines is for "present last 5 entries with entry.score == player.score - 1"

I want to remove this behavior and replace with : 
"display all solutions where entry.score == player.score - 1"
Because it would be easier with one mongo query

------

Also, do you want to keep
`# non-competitors can see bottom 20%` ?

And I can replace it with the 'display worth score' 

But this part is less problematic currently.

**Comment by towc** [comment] 2018-06-10 01:21
I think it's worth keeping the `index - 5`, for more varied answers, which is important to help people keep creative. Even with an additional mongo query, it's still going to be various orders of magnitude faster/more usable than without pagination

**Comment by igrigorik** [comment] 2018-06-10 18:06
@Hettomei @towc don't have a strong opinion on this one. I do want to make sure that we preserve the  "you can only see solutions slightly better than your own" behavior, but outside of those parameters I think we can experiment and be flexible. 

We could try @Hettomei's suggested behavior and, if necessary, it's trivial to subset the results to a smaller set — while not optimal, we could even do it in ruby-land after receiving the data back. WDYT?

**Comment by Hettomei** [comment] 2018-06-15 14:56
Starting PR at #248

**Comment by Hettomei** [comment] 2018-07-19 00:48
For people watching this issue : is it possible for you to check #248 which is ready to merge ?

**Comment by igrigorik** [comment] 2018-07-28 17:01
Resolved via above.

**Closed by igrigorik** 2018-07-28 17:01 UTC
Labels: feature
