### ISSUE TITLE
Unknown option argument: "-Z"

### ISSUE THREAD

**Issue by Pivert** [igrigorik/vimgolf#347] opened 2022-05-16 10:03 UTC
```
10:00:30[francoisd-XPS-pynvim-21357][francoisd] /workdir
$vimgolf put 9v006233d72d000000000219
Downloading Vimgolf challenge: 9v006233d72d000000000219
Launching VimGolf session for challenge: 9v006233d72d000000000219
vim: Unknown option argument: "-Z"
More info with "vim -h"
          Uh oh, Vim did not exit properly.
          Please ensure you can execute 'Vim' from the commandline.
          If the problem persists, please report the error on github.com/igrigorik/vimgolf

10:01:04[francoisd-XPS-pynvim-21357][francoisd] /workdir
$vim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@6ca0f4b974f4

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

Problem: vim (neovim) does not have the -Z command line option

**Comment by filbranden** [comment] 2022-08-28 03:47
Duplicate of #304

**Closed by filbranden** 2022-08-28 03:47 UTC
